const provinces = [
  // Miền Bắc
  { name: "Hà Nội", type: "PROVINCE" },
  { name: "Hải Phòng", type: "PROVINCE" },
  { name: "Hải Dương", type: "PROVINCE" },
  { name: "Hưng Yên", type: "PROVINCE" },
  { name: "Thái Bình", type: "PROVINCE" },
  { name: "Nam Định", type: "PROVINCE" },
  { name: "Hà Nam", type: "PROVINCE" },
  { name: "Ninh Bình", type: "PROVINCE" },
  { name: "Bắc Ninh", type: "PROVINCE" },
  { name: "Bắc Giang", type: "PROVINCE" },
  { name: "Lạng Sơn", type: "PROVINCE" },
  { name: "Cao Bằng", type: "PROVINCE" },
  { name: "Thái Nguyên", type: "PROVINCE" },
  { name: "Bắc Kạn", type: "PROVINCE" },
  { name: "Tuyên Quang", type: "PROVINCE" },
  { name: "Hà Giang", type: "PROVINCE" },
  { name: "Phú Thọ", type: "PROVINCE" },
  { name: "Vĩnh Phúc", type: "PROVINCE" },
  { name: "Yên Bái", type: "PROVINCE" },
  { name: "Lào Cai", type: "PROVINCE" },
  { name: "Hoà Bình", type: "PROVINCE" },
  { name: "Sơn La", type: "PROVINCE" },
  { name: "Điện Biên", type: "PROVINCE" },
  { name: "Lai Châu", type: "PROVINCE" },
  { name: "Quảng Ninh", type: "PROVINCE" },

  // Miền Trung
  { name: "Thanh Hoá", type: "PROVINCE" },
  { name: "Nghệ An", type: "PROVINCE" },
  { name: "Hà Tĩnh", type: "PROVINCE" },
  { name: "Quảng Bình", type: "PROVINCE" },
  { name: "Quảng Trị", type: "PROVINCE" },
  { name: "Thừa Thiên Huế", type: "PROVINCE" },
  { name: "Đà Nẵng", type: "PROVINCE" },
  { name: "Quảng Nam", type: "PROVINCE" },
  { name: "Quảng Ngãi", type: "PROVINCE" },
  { name: "Bình Định", type: "PROVINCE" },
  { name: "Phú Yên", type: "PROVINCE" },
  { name: "Khánh Hoà", type: "PROVINCE" },
  { name: "Ninh Thuận", type: "PROVINCE" },
  { name: "Bình Thuận", type: "PROVINCE" },

  // Tây Nguyên
  { name: "Kon Tum", type: "PROVINCE" },
  { name: "Gia Lai", type: "PROVINCE" },
  { name: "Đắk Lắk", type: "PROVINCE" },
  { name: "Đắk Nông", type: "PROVINCE" },
  { name: "Lâm Đồng", type: "PROVINCE" },

  // Miền Nam
  { name: "Bình Phước", type: "PROVINCE" },
  { name: "Tây Ninh", type: "PROVINCE" },
  { name: "Bình Dương", type: "PROVINCE" },
  { name: "Đồng Nai", type: "PROVINCE" },
  { name: "Bà Rịa - Vũng Tàu", type: "PROVINCE" },
  { name: "TP Hồ Chí Minh", type: "PROVINCE" },
  { name: "Long An", type: "PROVINCE" },
  { name: "Tiền Giang", type: "PROVINCE" },
  { name: "Bến Tre", type: "PROVINCE" },
  { name: "Trà Vinh", type: "PROVINCE" },
  { name: "Vĩnh Long", type: "PROVINCE" },
  { name: "Đồng Tháp", type: "PROVINCE" },
  { name: "An Giang", type: "PROVINCE" },
  { name: "Kiên Giang", type: "PROVINCE" },
  { name: "Cần Thơ", type: "PROVINCE" },
  { name: "Hậu Giang", type: "PROVINCE" },
  { name: "Sóc Trăng", type: "PROVINCE" },
  { name: "Bạc Liêu", type: "PROVINCE" },
  { name: "Cà Mau", type: "PROVINCE" },
];

export const organizations = [...provinces];
